namr: My First workflow
on:
  push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo "Hello, World!"

      - name: Run a multi-line script
        run: |
          echo "This is a multi-line script"
          echo "It can contain multiple commands"